table bigEnsembl
"bigGenePred gene models with extra fields for Ensembl"
   (
   string chrom;       "Reference chromosome"
   uint   chromStart;  "Start position in chromosome"
   uint   chromEnd;    "End position in chromosome"
   string name;        "Transcript identifier"
   uint score;         "Score [not used]"
   char[1] strand;     "+ or - for strand"
   uint thickStart;    "Beginning of CDS region"
   uint thickEnd;      "End of CDS region"
   uint reserved;       "RGB value"
   int blockCount;     "Number of blocks"
   int[blockCount] blockSizes; "Comma separated list of block sizes"
   int[blockCount] chromStarts; "Start positions relative to chromStart"
   string name2;       "Gene symbol"
   string cdsStartStat; "Status of CDS start annotation [not used]"
   string cdsEndStat;   "Status of CDS end annotation  [not used]"
   int[blockCount] exonFrames; "Exon frame {0,1,2}, or -1 if no frame for exon"
   string type;        "Transcript type"
   string geneName;    "Gene identifier"
   string geneName2;   "Gene symbol"
   string geneType;    "Gene type"
   string geneDescription;  "Gene description"
   string parentGene;   "Parent gene for HPRC mapping"
   string mappingType;  "HPRC mapping type"
   string parentGeneDisplayXref;  "Parent gene display name, symbol if available"
   )

